# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/workspace/serialplotter/serialPlotter/CalibrationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Clibration(object):
    def setupUi(self, Clibration):
        Clibration.setObjectName("Clibration")
        Clibration.resize(612, 407)
        self.gridLayout = QtWidgets.QGridLayout(Clibration)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Clibration)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(Clibration)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 1)

        self.retranslateUi(Clibration)
        QtCore.QMetaObject.connectSlotsByName(Clibration)

    def retranslateUi(self, Clibration):
        _translate = QtCore.QCoreApplication.translate
        Clibration.setWindowTitle(_translate("Clibration", "Form"))
        self.label.setText(_translate("Clibration", "Data stream"))
